---
- hosts: csr1
  gather_facts: no
  tasks:
    - name: Generate Baseline
      template: 
        src: "/home/edadmin/git/AWX/playbooks/baseline/router.j2"
        dest: "{{ playbook_dir }}/router.cfg"
