---
- name: Create a VM from a template
  hosts: servers
  connection: local
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
  - name: Create Windows Server 2012 VM
    vmware_guest:
      hostname: 172.16.1.146
      username: "{{ vmware_user }}"
      password: "{{ vmware_password }}"
      validate_certs: False
      esxi_hostname: 172.16.1.147
      folder: ProdVM
      name: DC50
      template: Win2k12_Template
      datacenter: Datacenter
      datastore: Datastore HDD-147
      state: poweredoff
      wait_for_ip_address: no