---
- hosts: iosxe
  gather_facts: no
  vars_files:
    - "{{ playbook_dir }}/group_vars/flex.yml"

  tasks:
    - name: Configure Flex from Template
      template: src="{{ playbook_dir }}/templates/flex.j2" dest="{{ playbook_dir }}/flex.cfg"

    - name: Configure Flex from Config File
      ios_config:
        src: "{{ playbook_dir }}/flex.cfg"