---
- hosts: routers_iosxe
  gather_facts: no
  vars_files:
    - "{{ playbook_dir }}/group_vars/all.yml"
    - "{{ playbook_dir }}/group_vars/vault.yml"
  tasks:
    - name: Create Configs from Template
      template: src="{{ playbook_dir }}/templates/jmc.j2" dest="{{ playbook_dir }}/jmc.cfg"

    - name: Apply Configs
      ios_config:
        src: "{{ playbook_dir }}/jmc.cfg"