---
- hosts: all
  gather_facts: no
  vars_files:
    - "{{ playbook_dir }}/group_vars/jmc.yml"
  tasks:
    - name: Create Configs from Template
      template: src="{{ playbook_dir }}/templates/jmc.j2" dest="{{ playbook_dir }}/jmc.cfg"

    # - name: Apply Configs
      # ios_config:
        # src: "{{ playbook_dir }}/jmc.cfg"