---
- hosts: iosxe
  gather_facts: no
  vars_files:
    - "{{ playbook_dir }}/group_vars/keys.yml"

  tasks:
    - name: Create Configs from Template
      template:
        src: "{{ playbook_dir }}/templates/eigrp_keychain.j2"
        dest: "{{ playbook_dir }}/eigrp_keychain.cfg"

    - name: Adding Keychain
      ios_config:
        src: "{{ playbook_dir }}/eigrp_keychain.cfg"