---
- hosts: iosxe
  gather_facts: no
  tasks:
    - name: Revert to Base Config
      cisco.ios.ios_command:
        commands:
          - command: 'config replace bootflash:base'
            prompt:
              - '.*'
            answer:
              - 'Y'
              - "\r"
