---
- hosts: 192.168.199.11
  gather_facts: no

  tasks:
    - name: Create Loopback999
      ios_interfaces:
        config:
          - name: Loopback999
            description: Configured with Ansible
            enabled: true