---
- name: TEST
  gather_facts: false
  hosts: routers
  vars:
    ios_provider:
      username: {{ un }}
      password: {{ pwd }}
      
  tasks:
  - name: RUN COMMANDS IN PB
    ios_commands:
      commands:
        - 'conf t'
        - 'ip ssh version 2'
        - 'do wr'